# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 28f1f3a14800120ee3374b16b28e65d5b15b486a78d4cfe3793f3a9d704953fde5b8b10b252c2fe41a1e39b9e67857624671e2642833176d6d01d61f666feb91

test:
  secret_key_base: 8079e7542864419c08c68416168af85c78e890698dda7e49b839f00458fc9fe166c5dbd0a4d363434a12b9fa5b08d8160e4c85e71f434e7e33129151419b924d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
